### ISSUE TITLE
LoganSquare 1.3.4 compile error, "cannot find symbol" with another class as array field

### ISSUE THREAD

**Issue by talklittle** [bluelinelabs/LoganSquare#118]
For example, `ExampleObject$$JsonObjectMapper` gets generated with this parseField method:

```
  @Override
  public void parseField(ExampleObject instance, String fieldName, JsonParser jsonParser) throws IOException {
    if ("children".equals(fieldName)) {
      if (jsonParser.getCurrentToken() == JsonToken.START_ARRAY) {
        List<ExampleWithTCObject> collection1 = new ArrayList<ExampleWithTCObject>();
        while (jsonParser.nextToken() != JsonToken.END_ARRAY) {
          ExampleWithTCObject value1;
          value1 = getcom_example_ExampleWithTCObject_type_converter().parse(jsonParser);
          collection1.add(value1);
        }
        ExampleWithTCObject[] array = collection1.toArray(new ExampleWithTCObject[collection1.size()]);
        instance.setChildren(array);
      } else {
        instance.setChildren(null);
      }
    }
  }
```

And error:

> error: cannot find symbol method getcom_example_ExampleWithTCObject_type_converter()

Based on this JSON model:

```
@JsonObject
public class ExampleObject {

    @JsonField
    private ExampleWithTCObject[] children;
	
	public ExampleWithTCObject[] getChildren() {
		return children;
	}
	public void setChildren(ExampleWithTCObject[] children) {
		this.children = children;
	}
	
}
```

And initialized LoganSquare with:

```
LoganSquare.registerTypeConverter(ExampleWithTCObject.class, new ExampleTypeConverter());
```

(works fine with LoganSquare 1.3.3)

**Comment by EricKuck** [comment]
This is now released as 1.3.6. Thanks!
