### PR TITLE
DynamicFieldType: restore TypeConverter lookup

### LINKED ISSUE #118: LoganSquare 1.3.4 compile error, "cannot find symbol" with another class as array field
For example, `ExampleObject$$JsonObjectMapper` gets generated with this parseField method:

```
  @Override
  public void parseField(ExampleObject instance, String fieldName, JsonParser jsonParser) throws IOException {
    if ("children".equals(fieldName)) {
      if (jsonParser.getCurrentToken() == JsonToken.START_ARRAY) {
        List<ExampleWithTCObject> collection1 = new ArrayList<ExampleWithTCObject>();
        while (jsonParser.nextToken() != JsonToken.END_ARRAY) {
          ExampleWithTCObject value1;
          value1 = getcom_example_ExampleWithTCObject_type_converter().parse(jsonParser);
          collection1.add(value1);
        }
        ExampleWithTCObject[] array = collection1.toArray(new ExampleWithTCObject[collection1.size()]);
        instance.setChildren(array);
      } else {
        instance.setChildren(null);
      }
    }
  }
```

And error:

> error: cannot find symbol method getcom_example_ExampleWithTCObject_type_converter()

Based on this JSON model:

```
@JsonObject
public class ExampleObject {

    @JsonField
    private ExampleWithTCObject[] children;
	
	public ExampleWithTCObject[] getChildren() {
		return children;
	}
	public void setChildren(ExampleWithTCObject[] children) {
		this.children = children;
	}
	
}
```

And initialized LoganSquare with:

```
LoganSquare.registerTypeConverter(ExampleWithTCObject.class, new ExampleTypeConverter());
```

(works fine with LoganSquare 1.3.3)

### PR DESCRIPTION
**Pull request by talklittle**
This was changed between LoganSquare 1.3.3 and 1.3.4.

Reverting this change fixes the compile-time error.

fixes GH-118

### CODE REVIEW

**Comment by EricKuck** [comment]
Thanks @talklittle! Will be releasing an update that includes this within a few hours.

**Comment by EricKuck** [comment]
I actually ended up reverting this PR and fixing it a different way. Since creating TypeConverters can theoretically be expensive, the new change in 1.3.7 should ensure that they're only ever created once. If you have any issues with 1.3.7 vs. 1.3.6, please let me know.

**Comment by talklittle** [comment]
@EricKuck Thanks! 1.3.7 works great. Tested with ProGuard also.
